### ISSUE TITLE
Fix errors in run_train_represent.ipynb

### ISSUE THREAD

**Issue by PraAnj** [zcakhaa/DeepLOB-Deep-Convolutional-Neural-Networks-for-Limit-Order-Books#1]
There are few errors in the notebook in your repo. Please fix them. Also add a direct link to the data source so readers can directly download them.

https://etsin.fairdata.fi/dataset/73eb48d7-4dbc-4a10-a52a-da745b47a649

**Comment by lorrp1** [comment]
hello, 
could you describe these errors?
