### ISSUE TITLE
Which version of keras?

### ISSUE THREAD

**Issue by deancorleone00** [zcakhaa/DeepLOB-Deep-Convolutional-Neural-Networks-for-Limit-Order-Books#2]
While running the code with the latest version of Keras, I get 

ImportError: cannot import name 'CuDNNLSTM' from 'keras.layers'

After searching for awhile, I found out that CuDNNLSTM is deprecated, may I know which version of Keras should I use for this notebook?

Thanks!
Dean

**Comment by zcakhaa** [comment]
I am using Tensorflow 1, but it should be compatible with Tensorflow 2. You can just use LSTM instead of CuDNNLSTM.

________________________________

**Comment by deancorleone00** [comment]
Thanks, I will try with tf v1
