### ISSUE TITLE
LSE是等事件宽度截面还是等时间宽度的截面

### ISSUE THREAD

**Issue by chinaliwenbo** [zcakhaa/DeepLOB-Deep-Convolutional-Neural-Networks-for-Limit-Order-Books#23]
牛津大佬，论文很厉害，受教了，有两个问题想请教一下。
1、LSE上的预测的时候，输入的数据是按照时间等分取出来的order_book截面，还是跟fi-2010一样，按照事件等分呢。
2、DBLOB里面，bayeis交易策略，出场那个不是很明白，”We exit the position if H < β2. In
next section, we show how these trading parameters affect our profits and risk level.“ 这里是不是要同时满足p(t) < \alpha 呢。

**Comment by zcakhaa** [comment]
hello 谢谢


  1.  不是时间等分的，就是tick级别的快照
  2.  出的时候应该就是 H 小于beta2就好了，

________________________________
From: liwb ***@***.***>
Sent: Sunday, September 25, 2022 4:34 PM
To: zcakhaa/DeepLOB-Deep-Convolutional-Neural-Networks-for-Limit-Order-Books ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [zcakhaa/DeepLOB-Deep-Convolutional-Neural-Networks-for-Limit-Order-Books] LSE是等事件截面还是等时间的截面 (Issue #23)


牛津大佬，论文很厉害，受教了，有两个问题想请教一下。
1、LSE上的预测的时候，输入的数据是按照时间等分取出来的order_book截面，还是跟fi-2010一样，按照事件等分呢。
2、DBLOB里面，bayeis交易策略，出场那个不是很明白，”We exit the position if H < β2. In
next section, we show how these trading parameters affect our profits and risk level.“ 这里是不是要同时满足p(t) < \alpha 呢。

―
