### ISSUE TITLE
how can you train 6m LSE data by the method fit

### ISSUE THREAD

**Issue by willinglion** [zcakhaa/DeepLOB-Deep-Convolutional-Neural-Networks-for-Limit-Order-Books#4]
hi,
deeplob.fit(trainX_CNN, trainY_CNN, epochs=200, batch_size=64, verbose=2, validation_data=(testX_CNN, testY_CNN))
this is the only train method I find in the code. In the paper, you use 6m LSE data as train data and 3m as validation data. But I can not use fit to train them, the data is too huge.

**Comment by zcakhaa** [comment]
It is usually a memory problem. You just need to split your data into chunks, train your model with one chunk, and keep doing it.

________________________________

**Comment by willinglion** [comment]
you only use fit, and do not use fit_generator()? do the chunks include train data and validation data together?

**Comment by zcakhaa** [comment]
You don't necessarily need to use fit_generator(). You can validate once you have trained your model on the full training data for one epoch. Essentially, you just split training data into small parts and randomly load each small part and train.



________________________________

**Comment by willinglion** [comment]
thank you.
